### ISSUE TITLE
How to install/use?

### ISSUE THREAD

**Issue by epinault** [tenderlove/av_capture#1]
I tried installing the 2 gem needed in the Rakefile and ran rake. 

But seems like I need to compile something? What steps am I missing?

```
gem install hoe rake-compiler
```

```
rake
Defaulting gemspec to MIT license.
Call license in hoe spec to change.
/Users/Emmanuel/.rubies/ruby-2.1.0-preview2/bin/ruby -w -Ilib:bin:test:. -e 'require "rubygems"; require "minitest/autorun"; require "test/test_maccam.rb"' -- 
/Users/Emmanuel/.rubies/ruby-2.1.0-preview2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- av_capture.so (LoadError)
    from /Users/Emmanuel/.rubies/ruby-2.1.0-preview2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/Emmanuel/Projects/av_capture/lib/av_capture.rb:1:in `<top (required)>'
    from /Users/Emmanuel/.rubies/ruby-2.1.0-preview2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/Emmanuel/.rubies/ruby-2.1.0-preview2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/Emmanuel/Projects/av_capture/test/test_maccam.rb:2:in `<top (required)>'
    from /Users/Emmanuel/.rubies/ruby-2.1.0-preview2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/Emmanuel/.rubies/ruby-2.1.0-preview2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
rake aborted!
Command failed with status (1): [/Users/Emmanu
```

**Comment by pnc** [comment]
Hi! If you just want to compile the library so you can work on it in-place, following the [instructions for rake-compiler](https://github.com/luislavena/rake-compiler#the-simple-process):

```
rake compile
```

If that succeeds, then run `rake` to run the test suite—your iSight should blink on and off a few times if everything is working.

If you just want to get the gem installed on your machine to use it in another project, run:

```
rake gem
gem install pkg/av_capture-1.0.0.gem
```

RubyGems will automatically build the native extension as part of the second step. You might need to `sudo` the `gem install` step if you're not using RVM or rbenv.

**Comment by epinault** [comment]
Oh thanks! I was not familiar with rake compiler. Use to the old ruby setup.rb in an ext folder :)   

It compiled and ran test fine and saw the light blinking.  Thanks for your help!  

## 

Emmanuel Pinault
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by pnc** [comment]
Glad to hear it's working!

I forgot to reference this issue, but these instructions are now in the README (#2), so this should be a little clearer for anybody else using the gem. In addition, `rake compile` is now a dependency of `rake`, so it should happen automatically now.
