### ISSUE TITLE
Add Development dependency for minitest?

### ISSUE THREAD

**Issue by DanBradbury** [tenderlove/av_capture#5]
I know it's just a pet project but it may be worthwhile to toss minitest into development. 

Know that my rake failed because of minitest missing. Granted everyone who can read would be able to figure out they need to `gem install minitest`

**Comment by pnc** [comment]
The curse of already having it installed: never realizing! If you make a PR I'll definitely merge it.

**Comment by DanBradbury** [comment]
I have opened PR #6 which should fix this issue for folks like me.
